apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: propmarket
type: Opaque
stringData:
  DB_USERNAME: "propadmin"
  DB_PASSWORD: "admin123"
  JWT_SECRET:  "PropMarketJWTSecretKey2024VeryLongAndSecureKeyForProduction"
---
#kubectl create secret generic rds-ssl-cert \
#--from-file=global-bundle.pem \
#-n propmarket