apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: propmarket
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/propmarket-project.git
    targetRevision: main
    path: kubernetes-code
  destination:
    server: https://kubernetes.default.svc
    namespace: propmarket
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
