apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: propmarket
data:
  # ── Server ────────────────────────────────────────────────────
  SERVER_PORT: "8080"
#  SSL_CERT_PATH: "/app/certs/global-bundle.pem" already used as initcon
  CORS_ORIGINS: "http://www.goldbullet.shop"
  UPLOAD_DIR: "/app/uploads"
  # ── Spring Boot actuator ──────────────────────────────────────
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  SPRING_PROFILES_ACTIVE: "dev"